### ISSUE TITLE
返回NULL？ 支付失败

### ISSUE THREAD

**Issue by BadDeveloper2022** [tsy12321/PayAndroid#10]
可以调用微信，也可以分享。。。。签名，包名都正常....
服务器上获取的订单信息也正常...
但是启动微信后返回NULL ，支付失败

return_code: "SUCCESS",
return_msg: "OK",
appid: "XXXXXXXX",
mch_id: "XXXXXXX",
nonce_str: "mHX3FWyAXYhlX2HM",
sign: "E5F8A91EE93E2BD06DD71CEFECFC3703",
result_code: "SUCCESS",
prepay_id: "wx2017011220561934f67262b80544980295",
trade_type: "APP",
package: "Sign=WXPay"

**Comment by BadDeveloper2022** [comment]
那个XXXX是正常的，我不想写在这里..

**Comment by tsy12321** [comment]
哪个方法返回null

**Comment by BadDeveloper2022** [comment]
微信回调的方法，

**Comment by BadDeveloper2022** [comment]
我们生成的sign和微信返回的sign一样吗？

**Comment by tsy12321** [comment]
不一样的。要自己加密

**Comment by BadDeveloper2022** [comment]
嗯，自己重新加密了....但是还是一样的错误 -1 ,errMsg=NULL 网上说的是签名或者包名不一致，但是我检查了，都一样的，签名的MD5都检查了一样......

**Comment by tsy12321** [comment]
return_code: "SUCCESS",
return_msg: "OK",

**Comment by tsy12321** [comment]
参数没有这2个啊

**Comment by BadDeveloper2022** [comment]
![image](https://cloud.githubusercontent.com/assets/7404699/21923348/7e2ca6e8-d9ae-11e6-81df-575dce9ac663.png)

**Comment by BadDeveloper2022** [comment]
APP里面有微信分享，那个功能正常....这个不知道什么问题，能不能帮我看看~！QQ 253933559

**Comment by tsy12321** [comment]
把你放到doPay的参数发出来我看看啊

**Comment by BadDeveloper2022** [comment]
http://api.XXX.com/nahxa/app_payparam.aspx

**Comment by tsy12321** [comment]
![image](https://cloud.githubusercontent.com/assets/9690656/22053540/4f12142e-dd8c-11e6-9150-4adcdb71a54a.png)
支付传入的是这几个参数，你有几个名字不对，而且多了参数.认真仔细核实下

**Comment by BadDeveloper2022** [comment]
![image](https://cloud.githubusercontent.com/assets/7404699/22053604/c4a09a1c-dd8c-11e6-87a4-c17e6fd728b2.png)
这些都正常...我根据自己的参数修改过你这儿的代码。。。

**Comment by tsy12321** [comment]
然后呢。onResp执行了？返回的errcode是什么

**Comment by BadDeveloper2022** [comment]
无法启动微信：
返回 -1 , errMsg= NULL 
我前面怀疑签名有问题，但是别的分享功能都正常，正常调用微信好友，朋友圈

**Comment by tsy12321** [comment]
签名的所有参数的拼写全部检查一遍。按照微信api，目测签名问题。不能有多余参数，也不能少，参数名一个字母也不能差等等。都检查一遍吧

**Comment by tsy12321** [comment]
分享的功能只要包名 android签名一致就行。
我说的签名是sign的生成，跟分享登录没有关系

**Comment by BadDeveloper2022** [comment]
好的！我检查看看！~谢谢 ，能不能发给我这个的完整版PHP签名部分的代码，谢谢 253933559@qq.com
我这个是Asp.net写的，我参考一下你的PHP代码，网上的不全。。。。
也想直接用你的php代码

**Comment by tsy12321** [comment]
https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=11_1

**Comment by tsy12321** [comment]
![image](https://cloud.githubusercontent.com/assets/9690656/22054191/3da520b6-dd8f-11e6-8555-df9881565d52.png)
下载php 可以参考哦。
