### ISSUE TITLE
有个困惑？

### ISSUE THREAD

**Issue by bingely** [tsy12321/PayAndroid#2]
微信支付可以吗？我没看到微信回调页面，这个一定要放到“App包名.wxapi”的package中,否则无法响应回调。请问作者试过了吗

**Comment by tsy12321** [comment]
试过的 我是把那个回调activity放在了sdk中。然后再AndroidManifest中用：

```
<activity-alias
            android:name=".wxapi.WXPayEntryActivity"
            android:exported="true"
            android:targetActivity="com.tsy.pay.weixin.WXPayCallbackActivity" />
```

可以省略WXPayEntryActivity的创建 它会直接使用sdk中的WXPayCallbackActivity进行回调处理。具体仔细看接入说明啊

**Comment by liuwen370494581** [comment]
<activity
        android:name="com.tsy.pay.weixin.WXPayCallbackActivity"
        android:configChanges="orientation|keyboardHidden|navigation|screenSize"
        android:launchMode="singleTop"
        android:theme="@android:style/Theme.Translucent.NoTitleBar" />

    <activity-alias
        android:name=".wxapi.WXPayEntryActivity"
        android:exported="true"
        android:targetActivity="com.tsy.pay.weixin.WXPayCallbackActivity" />


 android:targetActivity="com.tsy.pay.weixin.WXPayCallbackActivity" 
 android:name="com.tsy.pay.weixin.WXPayCallbackActivity"

导入楼主的这个module  然后 在功能清单中复制 这两个Activity  发现这两个Activity是没有找到 报红色的 这个是什么原因啊

**Comment by bingely** [comment]
不用找，已经指向了WXPayCallbackActivity，可以先去了解android:targetActivity的作用。具体仔细看接入说明

**Comment by tsy12321** [comment]
666.记得close issue

**Comment by sendtion** [comment]
@liuwen370494581 
应该这么写：com.tsy.sdk.pay.weixin.WXPayCallbackActivity

**Comment by tsy12321** [comment]
@liuwen370494581 抱歉啊 问题已经修复 感谢 @sendtion 指出

**Comment by szitguy** [comment]
这个问题可以进一步优化吗？例如我想引入你的这个library module后，不用在我的app module的manifest中配置任何东西，就可以直接用了。

**Comment by tsy12321** [comment]
这个没办法，已经是优化过了的。app里的manifest还是必须要写东西的

**Comment by szitguy** [comment]
我最近在做个类似的demo，把这些平台搞成一个lib，提供个callback，里面两个方法：成功or失败，正在研究如何能让别人配置一句gradle脚本就能使用
