### ISSUE TITLE
11月发布的新版支付宝SDK中：“支付服务生成的支付参数”，是由服务端生成吗？

### ISSUE THREAD

**Issue by Lsy1992** [tsy12321/PayAndroid#3]
我记得旧版SDK支付参数和付款信息是由APP生成，如订单号、签名、商品名称、价格等，现在新版咋用？

**Comment by tsy12321** [comment]
这些信息都应该是由服务端生成的哦！无论是旧版还是新版。

**Comment by tsy12321** [comment]
比如你点击选择一个物品支付。需要先到服务端获取这个物品的价格（如果在客户端生成的价格参数是不可靠的，比如买了一个10块钱的东西，他可以在客户端改为1块然后支付），然后生成订单号，商品名称，最后将所有参数和rsa秘钥进行签名（这个一定要放到服务端，放到客户端人家可以获取秘钥了）。最后所有生成的参数传回客户端，发起支付。
新版和旧版的区别其实就是支付参数中的paternerId换成了appid，其他流程没变的

**Comment by Lsy1992** [comment]
原来是这个道理啊！！我们之前做的支付一直都是把公私钥写死在APP里，服务器返回商品的价格和信息，生成orderInfo然后调用支付宝， 看来是我们做错了，那么APP这边需要存什么？新版只用放APP ID就行？

**Comment by tsy12321** [comment]
好像什么都不需要。你看下我封装的。所有信息都由服务端传过来就行了。

**Comment by Lsy1992** [comment]
嗯嗯好的谢谢，你这个jar版本还是旧了点，新的是2016/11/23的

**Comment by tsy12321** [comment]
给你个pull request的机会。哈哈！

**Comment by Lsy1992** [comment]
我也不懂怎么传
![oizswp4ra93z qzxy k e](https://cloud.githubusercontent.com/assets/12758497/20995359/7f136644-bd31-11e6-916a-69e30b52f4ef.gif)
