### ISSUE TITLE
请问appkey，privatekey如何配置

### ISSUE THREAD

**Issue by HeJingWei** [tsy12321/PayAndroid#7]
请问appkey，privatekey如何配置。构造方法中的param参数传入参数代表什么呢

**Comment by tsy12321** [comment]
appkey privatekey是在支付参数里的。建议放到服务端，作为生成加密后的pay_param才使用。客户端收到就行了。所以应该是配置在服务端

**Comment by HeJingWei** [comment]
pay_param是一个json数据类型的字符串吗？

**Comment by tsy12321** [comment]
是的 你可以看README 里的博客 里面有说明pay param是怎么生成的

**Comment by HeJingWei** [comment]
嗯，我看到了，谢谢你
