### ISSUE TITLE
请问微信支付的应用签名是要正式签名的apk吗？

### ISSUE THREAD

**Issue by HeJingWei** [tsy12321/PayAndroid#9]
在手机上根据包名由签名工具生成字符串，安装的apk必须是正式签名的吗？

**Comment by tsy12321** [comment]
不懂。。。。。

**Comment by HeJingWei** [comment]
微信开放平台提供了一个手机上的apk，用来输入对应包名生成签名的。这个签名跟手机装了项目有关系吗？项目是否需要正式签名的呢？

**Comment by tsy12321** [comment]
需要 开发的app只有包名和签名和微信开放平台填的一致才能发起支付

**Comment by HeJingWei** [comment]
也就是说，填入开放平台的是由正式签名的APK生成的签名对吧

**Comment by tsy12321** [comment]
对的

**Comment by HeJingWei** [comment]
好的，了解，谢谢~
